### ISSUE TITLE
Can you please explain the restore options more?

### ISSUE THREAD

**Issue by alager** [sixninetynine/surrogate#23]
Maybe even add some examples?

>  -r Restore using default digest location

What exactly does this restore?  Can one specify the time, or version to restore?

> -c Restore, accepts a file containing a list of directories to restore.

Can you give an example of the usage here?  I'm not sure what is meant by directories to restore.  My mind says we would be restoring schemas/databases.

Thanks!

**Comment by infectormp** [comment]
`-r` restore to mysql dir last full backup with all incremental backups using `.digest` file from backup folder

**Comment by infectormp** [comment]
`-c` do same as `-r` but here you can specify file with backup list. 

better way to understand what they do run restore on test server or read the source code of surrogate.

**Comment by alager** [comment]
So is the -c option passed an argument similar to what the .digest file has, but modified to be what we would want to restore?

**Comment by lorencarvalho** [comment]
>  So is the -c option passed an argument similar to what the .digest file has, but modified to be what we would want to restore?

that's correct!

**Comment by lorencarvalho** [comment]
the reason that it restores "directories" and not schemas/databases is due to the way that `innobackupex` takes backups -- it's not like a mysqldump where you get something you can load by piping into a `mysql` client, innobackupex files are data files that can only be restored using `innobackupex`

**Comment by g011um** [comment]
Sorry to open up an old issue (I can open a new one if that's preferred), but my question is directly related to the previous discussion regarding the `-c` restore option.

If I want to restore a single database (rather than the complete nightly backup) can I give the path to database directory within the nightly backup, like:

`/data/backups/daily/Mon/full_2017-10-25_0600/database_name`

I see that xtrabackup supports a `--databases` option (see https://www.percona.com/doc/percona-xtrabackup/2.3/xtrabackup_bin/xbk_option_reference.html) that allows a list of databases/tables for restore to be listed.  Is there some way that could/should be used?

Thanks!

**Comment by tmrhymer** [comment]
@g011um - I am wondering this as well. Have you found the answer yet?

**Comment by tarjei** [comment]
Hi, to restore a single database, I think you can do the following:

1. On a different machine: Restore the COMPLETE backup
2. Export the db to a single file using mysqldump
3. Import that to the main db.
